import json
from datetime import datetime, timezone
from pathlib import Path

from django.conf import settings
from django.core.files.storage import default_storage
from django.core.management.base import BaseCommand, CommandError

from core.r2_cleanup import (
    ReferenceCollector,
    clean_object_key,
    collect_website_references,
    format_bytes,
    manifest_payload,
    r2_hosts,
    write_json,
)


CONFIRMATION = "DELETE-UNUSED-R2"


class Command(BaseCommand):
    help = (
        "Audit the configured Cloudflare R2 media namespace and, only with a "
        "reviewed manifest plus explicit confirmation, delete unused objects."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--manifest",
            help="Dry-run output path, or the reviewed manifest required by --delete.",
        )
        parser.add_argument(
            "--delete",
            action="store_true",
            help="Delete still-unused objects listed in a reviewed dry-run manifest.",
        )
        parser.add_argument(
            "--verify",
            action="store_true",
            help="Revalidate every object in an existing manifest without deleting anything.",
        )
        parser.add_argument(
            "--verified-manifest",
            help="Output path for the verified-only manifest generated by --verify.",
        )
        parser.add_argument(
            "--confirm",
            help=f"Required with --delete; must be exactly {CONFIRMATION}.",
        )
        parser.add_argument(
            "--log-file",
            help="Optional JSON Lines deletion log path (defaults beside the manifest).",
        )

    def handle(self, *args, **options):
        storage, client, bucket, prefix = self._r2_context()
        objects = self._list_objects(client, bucket)
        object_keys = {item["normalized_key"] for item in objects}
        collector = ReferenceCollector(
            object_keys,
            location=getattr(storage, "location", ""),
            bucket_name=bucket,
            allowed_hosts=r2_hosts(storage),
        )
        collect_website_references(collector)
        used = collector.used_keys
        active = [item for item in objects if item["normalized_key"] in used]
        managed = [item for item in objects if item["normalized_key"].startswith(prefix)]
        unused = [item for item in managed if item["normalized_key"] not in used]
        outside = [item for item in objects if not item["normalized_key"].startswith(prefix)]

        self._print_report(objects, active, unused, outside, prefix)
        if options["verify"]:
            if options["delete"]:
                raise CommandError("Choose either --verify or --delete, never both.")
            if options["confirm"]:
                raise CommandError("--confirm is not accepted during read-only verification.")
            self._verify_manifest(
                client=client,
                bucket=bucket,
                prefix=prefix,
                current_objects={item["key"]: item for item in objects},
                current_unused={item["key"] for item in unused},
                manifest_path=options["manifest"],
                verified_manifest_path=options["verified_manifest"],
            )
            return
        if options["delete"]:
            self._delete_from_manifest(
                client=client,
                bucket=bucket,
                prefix=prefix,
                current_objects={item["key"]: item for item in objects},
                current_unused={item["key"] for item in unused},
                manifest_path=options["manifest"],
                confirmation=options["confirm"],
                log_file=options["log_file"],
            )
            return

        if options["confirm"]:
            raise CommandError("--confirm is only valid together with --delete.")
        if options["verified_manifest"]:
            raise CommandError("--verified-manifest is only valid together with --verify.")
        manifest_path = options["manifest"] or self._default_manifest_path()
        payload = manifest_payload(
            bucket=bucket,
            prefix=prefix,
            objects=unused,
            generated_at=datetime.now(timezone.utc).isoformat(),
        )
        try:
            saved_path = write_json(manifest_path, payload)
        except FileExistsError as exc:
            raise CommandError(
                f"Refusing to overwrite existing manifest: {manifest_path}"
            ) from exc
        self.stdout.write(self.style.SUCCESS(f"Dry-run manifest: {saved_path}"))
        self.stdout.write("No R2 objects were deleted.")

    def _r2_context(self):
        if not getattr(settings, "R2_ENABLED", False):
            raise CommandError("R2 cleanup refused: R2_ENABLED is not active.")
        backend = settings.STORAGES.get("default", {}).get("BACKEND", "")
        if "storages.backends.s3" not in backend:
            raise CommandError("R2 cleanup refused: default storage is not the configured S3/R2 backend.")
        location = clean_object_key(getattr(default_storage, "location", ""))
        if not location:
            raise CommandError("R2 cleanup refused: the configured storage location/prefix is empty.")
        bucket = getattr(default_storage, "bucket_name", "")
        connection = getattr(default_storage, "connection", None)
        client = getattr(getattr(connection, "meta", None), "client", None)
        if not bucket or client is None:
            raise CommandError("R2 cleanup refused: bucket/client configuration is unavailable.")
        return default_storage, client, bucket, f"{location}/"

    def _list_objects(self, client, bucket):
        objects = []
        paginator = client.get_paginator("list_objects_v2")
        for page in paginator.paginate(Bucket=bucket):
            for item in page.get("Contents", []):
                modified = item.get("LastModified")
                raw_key = str(item["Key"])
                objects.append({
                    # Preserve the exact key for head/delete calls. The
                    # normalized form is comparison-only.
                    "key": raw_key,
                    "normalized_key": clean_object_key(raw_key),
                    "size": int(item.get("Size", 0)),
                    "etag": str(item.get("ETag", "")).strip('"'),
                    "last_modified": modified.isoformat() if modified else "",
                })
        return sorted(objects, key=lambda item: item["key"])

    def _print_report(self, objects, active, unused, outside, prefix):
        recoverable = sum(item["size"] for item in unused)
        self.stdout.write(f"Total R2 objects: {len(objects)}")
        self.stdout.write(f"Active/used objects: {len(active)}")
        self.stdout.write(f"Unused objects: {len(unused)}")
        self.stdout.write(f"Protected outside {prefix}: {len(outside)}")
        self.stdout.write(f"Total space recoverable: {format_bytes(recoverable)}")
        self.stdout.write("Unused keys/files:")
        if not unused:
            self.stdout.write("  (none)")
        for item in unused:
            self.stdout.write(f"  {item['key']} ({format_bytes(item['size'])})")

    def _delete_from_manifest(
        self, *, client, bucket, prefix, current_objects, current_unused,
        manifest_path, confirmation, log_file,
    ):
        if confirmation != CONFIRMATION:
            raise CommandError(
                f"Deletion refused: pass --confirm {CONFIRMATION} after reviewing the dry run."
            )
        if not manifest_path:
            raise CommandError("Deletion refused: --manifest is required with --delete.")
        try:
            manifest = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise CommandError(f"Cannot read reviewed manifest: {manifest_path}") from exc
        if manifest.get("version") != 1:
            raise CommandError("Deletion refused: unsupported manifest version.")
        if manifest.get("bucket") != bucket or manifest.get("managed_prefix") != prefix:
            raise CommandError("Deletion refused: manifest bucket/prefix does not match this environment.")

        candidates = manifest.get("unused_objects")
        if not isinstance(candidates, list):
            raise CommandError("Deletion refused: manifest has no valid unused object list.")
        log_path = Path(log_file) if log_file else Path(manifest_path).with_suffix(".deletions.jsonl")
        log_path.parent.mkdir(parents=True, exist_ok=True)
        deleted = skipped = failed = 0
        with log_path.open("a", encoding="utf-8") as audit_log:
            for expected in candidates:
                key = str(expected.get("key", ""))
                current = current_objects.get(key)
                if (
                    current is None
                    or not current.get("normalized_key", clean_object_key(key)).startswith(prefix)
                    or key not in current_unused
                    or current["size"] != expected.get("size")
                    or current["etag"] != expected.get("etag", "")
                ):
                    skipped += 1
                    self.stdout.write(self.style.WARNING(f"SKIPPED changed/active/missing: {key}"))
                    continue
                try:
                    head = client.head_object(Bucket=bucket, Key=key)
                    head_etag = str(head.get("ETag", "")).strip('"')
                    if int(head.get("ContentLength", -1)) != current["size"] or head_etag != current["etag"]:
                        skipped += 1
                        self.stdout.write(self.style.WARNING(f"SKIPPED changed before delete: {key}"))
                        continue
                    client.delete_object(Bucket=bucket, Key=key)
                    entry = {
                        "deleted_at": datetime.now(timezone.utc).isoformat(),
                        "bucket": bucket,
                        "key": key,
                        "size": current["size"],
                        "etag": current["etag"],
                    }
                    audit_log.write(json.dumps(entry, sort_keys=True) + "\n")
                    audit_log.flush()
                    deleted += 1
                    self.stdout.write(self.style.SUCCESS(f"DELETED {key} ({format_bytes(current['size'])})"))
                except Exception as exc:
                    failed += 1
                    self.stderr.write(self.style.ERROR(f"FAILED {key}: {exc}"))

        self.stdout.write(
            f"Deletion complete: {deleted} deleted, {skipped} skipped, {failed} failed."
        )
        self.stdout.write(f"Deletion log: {log_path}")
        if failed:
            raise CommandError("One or more R2 deletions failed; review the deletion log and output.")

    def _verify_manifest(
        self, *, client, bucket, prefix, current_objects, current_unused,
        manifest_path, verified_manifest_path,
    ):
        if not manifest_path:
            raise CommandError("Verification refused: --manifest is required with --verify.")
        try:
            manifest = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise CommandError(f"Cannot read manifest: {manifest_path}") from exc
        if manifest.get("version") != 1:
            raise CommandError("Verification refused: unsupported manifest version.")
        if manifest.get("bucket") != bucket or manifest.get("managed_prefix") != prefix:
            raise CommandError("Verification refused: manifest bucket/prefix does not match this environment.")
        candidates = manifest.get("unused_objects")
        if not isinstance(candidates, list):
            raise CommandError("Verification refused: manifest has no valid unused object list.")

        verified = []
        skipped = []
        verified_at = datetime.now(timezone.utc).isoformat()
        for index, expected in enumerate(candidates, start=1):
            key = str(expected.get("key", ""))
            current = current_objects.get(key)
            reason = ""
            if current is None:
                reason = "missing from current R2 listing"
            elif not current["normalized_key"].startswith(prefix):
                reason = "outside protected managed prefix"
            elif key not in current_unused:
                reason = "now active/referenced"
            elif current["size"] != expected.get("size"):
                reason = "size changed since manifest"
            elif current["etag"] != expected.get("etag", ""):
                reason = "ETag changed since manifest"
            elif current.get("last_modified", "") != expected.get("last_modified", ""):
                reason = "last-modified time changed since manifest"
            else:
                try:
                    head = client.head_object(Bucket=bucket, Key=key)
                    head_etag = str(head.get("ETag", "")).strip('"')
                    head_size = int(head.get("ContentLength", -1))
                    head_modified = head.get("LastModified")
                    current_modified = current.get("last_modified", "")
                    if head_size != current["size"]:
                        reason = "size changed during verification"
                    elif head_etag != current["etag"]:
                        reason = "ETag changed during verification"
                    elif head_modified and current_modified:
                        # Cloudflare R2 HEAD responses use whole-second HTTP
                        # dates, while list_objects_v2 includes milliseconds.
                        # Compare only the precision shared by both APIs. The
                        # current listing still has to match the reviewed
                        # manifest exactly above.
                        listed_modified = datetime.fromisoformat(current_modified)
                        if head_modified.replace(microsecond=0) != listed_modified.replace(microsecond=0):
                            reason = "last-modified time changed during verification"
                except Exception as exc:
                    reason = f"metadata recheck failed: {exc}"

            if reason:
                skipped.append({"key": key, "reason": reason})
                self.stdout.write(self.style.WARNING(f"SKIPPED {key}: {reason}"))
            else:
                verified.append({
                    "key": current["key"],
                    "size": current["size"],
                    "etag": current["etag"],
                    "last_modified": current.get("last_modified", ""),
                    "normalized_reference_count": 0,
                    "verified_at": verified_at,
                })
            if index % 50 == 0 or index == len(candidates):
                self.stdout.write(f"Verified metadata: {index}/{len(candidates)} candidates checked")

        output_path = (
            Path(verified_manifest_path)
            if verified_manifest_path
            else Path(manifest_path).with_name(f"{Path(manifest_path).stem}.verified.json")
        )
        payload = {
            "version": 1,
            "generated_at": verified_at,
            "verified_from": str(manifest_path),
            "bucket": bucket,
            "managed_prefix": prefix,
            "verification": {
                "reference_scan": "all database file/text/JSON fields, settings, and application source",
                "required_normalized_reference_count": 0,
                "metadata_rechecked_with_head_object": True,
                "skipped_objects": skipped,
            },
            "unused_objects": verified,
        }
        try:
            saved_path = write_json(output_path, payload)
        except FileExistsError as exc:
            raise CommandError(
                f"Refusing to overwrite existing verified manifest: {output_path}"
            ) from exc

        recoverable = sum(item["size"] for item in verified)
        self.stdout.write("Final manifest verification:")
        self.stdout.write(f"  Original candidates: {len(candidates)}")
        self.stdout.write(f"  Verified safe-to-delete: {len(verified)}")
        self.stdout.write(f"  Skipped/protected: {len(skipped)}")
        self.stdout.write(f"  Total recoverable space: {format_bytes(recoverable)}")
        self.stdout.write(self.style.SUCCESS(f"Verified-only manifest: {saved_path}"))
        self.stdout.write("No R2 objects were deleted.")

    def _default_manifest_path(self):
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        return settings.BASE_DIR / "r2_cleanup_reports" / f"dry-run-{timestamp}.json"
