# Generated by Django 5.2.16 on 2026-08-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_category_menu_label'),
        ('core', '0007_add_zeiss_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='equipment_group',
            field=models.CharField(blank=True, choices=[('laboratory', 'Laboratory'), ('medical', 'Medical Equipment'), ('dental', 'Dental Equipment')], help_text='Show this manufacturer in the Products & Solutions menu.', max_length=20),
        ),
        migrations.AddField(
            model_name='partner',
            name='menu_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories displayed beneath this manufacturer.', related_name='menu_manufacturers', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='partner',
            name='menu_label',
            field=models.CharField(blank=True, help_text='Optional shorter manufacturer name for the menu.', max_length=120),
        ),
        migrations.AddField(
            model_name='partner',
            name='menu_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
