# Generated by Django 5.2.16 on 2026-08-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_configure_product_navigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='menu_order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
