# Generated by Django 5.2.16 on 2026-09-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_customer_video_playback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='About Somlab', max_length=80)),
                ('hero_title', models.CharField(default='Built around reliable laboratory performance.', max_length=220)),
                ('hero_intro', models.TextField(default='Serving hospitals, private laboratories, universities, research organisations and clinics across East Africa.')),
                ('story_eyebrow', models.CharField(default='Who we are', max_length=80)),
                ('story_title', models.CharField(default='A laboratory solutions company with a long-term view.', max_length=220)),
                ('story_paragraph_one', models.TextField(default='Founded in 2022 as a sister company of Medisom Health Group, Somlab Diagnostics imports, distributes and installs quality laboratory equipment, reagents and supplies.')),
                ('story_paragraph_two', models.TextField(default='We support customers beyond delivery through training, maintenance, laboratory management systems and customised turnkey projects.')),
                ('vision_title', models.CharField(default='Our vision', max_length=80)),
                ('vision_body', models.TextField(default='To become a leading laboratory solutions provider in East Africa by delivering reliable products, excellent service and long-term value.')),
                ('mission_title', models.CharField(default='Our mission', max_length=80)),
                ('mission_body', models.TextField(default='To build lasting partnerships by providing quality laboratory products, innovative solutions and dependable technical support.')),
                ('promise_title', models.CharField(default='Our promise', max_length=80)),
                ('promise_body', models.TextField(default='We deliver what we promise and promise only what we can deliver—with integrity, care and consistent performance.')),
                ('values_eyebrow', models.CharField(default='Our values', max_length=80)),
                ('values_title', models.CharField(default='How we work', max_length=150)),
                ('integrity_title', models.CharField(default='Integrity', max_length=80)),
                ('integrity_body', models.TextField(default='Honesty, fairness and transparency in every relationship.')),
                ('reliability_title', models.CharField(default='Reliability', max_length=80)),
                ('reliability_body', models.TextField(default='Dependable products, communication and follow-through.')),
                ('teamwork_title', models.CharField(default='Teamwork', max_length=80)),
                ('teamwork_body', models.TextField(default='Working closely with customers, suppliers and technical teams.')),
                ('customer_focus_title', models.CharField(default='Customer focus', max_length=80)),
                ('customer_focus_body', models.TextField(default='Solutions shaped around the realities of each institution.')),
                ('service_excellence_title', models.CharField(default='Service excellence', max_length=80)),
                ('service_excellence_body', models.TextField(default='Responsive support delivered efficiently and professionally.')),
                ('audience_eyebrow', models.CharField(default='Who we serve', max_length=80)),
                ('audience_title', models.CharField(default='Supporting health and science across the region', max_length=180)),
                ('audiences', models.TextField(default='Hospitals\nPrivate laboratories\nClinics\nBlood banks\nUniversities\nResearch centres\nGovernment institutions\nHumanitarian organisations', help_text='One audience per line.')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Contact us', max_length=80)),
                ('hero_title', models.CharField(default='Let’s solve your laboratory requirement.', max_length=220)),
                ('hero_intro', models.TextField(default='Ask about products, availability, technical services or your current order.')),
                ('details_eyebrow', models.CharField(default='Somlab Diagnostics', max_length=80)),
                ('details_title', models.CharField(default='Talk to our team', max_length=150)),
                ('details_intro', models.TextField(default='We usually respond during business hours. For urgent product enquiries, call or WhatsApp our sales team.')),
                ('email', models.EmailField(default='info@somlab.so', max_length=254)),
                ('primary_phone', models.CharField(default='+252 616 119117', max_length=40)),
                ('secondary_phone', models.CharField(blank=True, default='+90 534 820 0301', max_length=40)),
                ('office_address', models.TextField(default='Star Home Tower, 5th Floor, Apt. 504\nKM5, Amira Hotel Street, Hodan District\nMogadishu, Somalia')),
                ('form_title', models.CharField(default='Send a message', max_length=120)),
            ],
        ),
    ]
