# Generated by Django 5.2.16 on 2026-09-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_normalize_customer_display_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('display_order',), name='unique_customer_display_order'),
        ),
    ]
