from django.urls import path
from . import views

urlpatterns = [
    path("inquiries/", views.inquiry_list, name="dashboard_inquiries"),
    path("inquiries/<str:inquiry_number>/", views.inquiry_detail, name="dashboard_inquiry_detail"),
    path("email-settings/", views.inquiry_email_settings, name="dashboard_email_settings"),
    path("about/", views.about_content, name="dashboard_about_content"),
    path("contact/", views.contact_content, name="dashboard_contact_content"),
    path("messages/", views.messages_list, name="dashboard_messages"),
    path("messages/<int:pk>/", views.message_detail, name="dashboard_message_detail"),
    path("products/", views.product_list, name="dashboard_products"),
    path("products/add/", views.product_create, name="dashboard_product_add"),
    path("products/<int:pk>/edit/", views.product_edit, name="dashboard_product_edit"),
    path("products/<int:pk>/delete/", views.product_delete, name="dashboard_product_delete"),
    path("categories/", views.category_list, name="dashboard_categories"),
    path("categories/add/", views.category_create, name="dashboard_category_add"),
    path("categories/<int:pk>/edit/", views.category_edit, name="dashboard_category_edit"),
    path("categories/<int:pk>/delete/", views.category_delete, name="dashboard_category_delete"),
    path("subcategories/", views.subcategory_list, name="dashboard_subcategories"),
    path("subcategories/add/", views.subcategory_create, name="dashboard_subcategory_add"),
    path("subcategories/<int:pk>/edit/", views.subcategory_edit, name="dashboard_subcategory_edit"),
    path("subcategories/<int:pk>/delete/", views.subcategory_delete, name="dashboard_subcategory_delete"),
    path("partners/", views.partner_list, name="dashboard_partners"),
    path("partners/add/", views.partner_create, name="dashboard_partner_add"),
    path("partners/<int:pk>/edit/", views.partner_edit, name="dashboard_partner_edit"),
    path("partners/<int:pk>/delete/", views.partner_delete, name="dashboard_partner_delete"),
    path("customers/", views.customer_list, name="dashboard_customers"),
    path("customers/add/", views.customer_create, name="dashboard_customer_add"),
    path("customers/<int:pk>/edit/", views.customer_edit, name="dashboard_customer_edit"),
    path("customers/<int:pk>/delete/", views.customer_delete, name="dashboard_customer_delete"),
    path("customers/<int:customer_pk>/projects/", views.customer_project_list, name="dashboard_customer_projects"),
    path("customers/<int:customer_pk>/projects/add/", views.customer_project_create, name="dashboard_customer_project_add"),
    path("customers/<int:customer_pk>/projects/<int:pk>/edit/", views.customer_project_edit, name="dashboard_customer_project_edit"),
    path("customers/<int:customer_pk>/projects/<int:pk>/delete/", views.customer_project_delete, name="dashboard_customer_project_delete"),
    path("customers/<int:customer_pk>/projects/<int:project_pk>/media/", views.customer_project_media_list, name="dashboard_customer_project_media"),
    path("customers/<int:customer_pk>/projects/<int:project_pk>/media/add/", views.customer_project_media_create, name="dashboard_customer_project_media_add"),
    path("customers/<int:customer_pk>/projects/<int:project_pk>/media/<int:pk>/edit/", views.customer_project_media_edit, name="dashboard_customer_project_media_edit"),
    path("customers/<int:customer_pk>/projects/<int:project_pk>/media/<int:pk>/delete/", views.customer_project_media_delete, name="dashboard_customer_project_media_delete"),
    path("services/", views.service_list, name="dashboard_services"),
    path("services/add/", views.service_create, name="dashboard_service_add"),
    path("services/<int:pk>/edit/", views.service_edit, name="dashboard_service_edit"),
    path("services/<int:pk>/delete/", views.service_delete, name="dashboard_service_delete"),
    path("users/", views.user_list, name="dashboard_users"),
    path("users/add/", views.user_create, name="dashboard_user_add"),
    path("users/<int:pk>/edit/", views.user_edit, name="dashboard_user_edit"),
]
