# Generated by Django 5.2.16 on 2026-08-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_zeiss_light_microscope_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu_label',
            field=models.CharField(blank=True, help_text='Optional shorter category name for navigation menus.', max_length=120),
        ),
    ]
