# Generated by Django 5.2.16 on 2026-08-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_vatech_dental_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='image',
            field=models.ImageField(blank=True, help_text="Optional image used for this subcategory's public hero area.", upload_to='subcategories/'),
        ),
    ]
