# Generated by Django 5.2.16 on 2026-08-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_productsubcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_image',
            field=models.ImageField(blank=True, editable=False, help_text='Original upload retained for safe image reprocessing.', upload_to='products/originals/'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='source_file',
            field=models.FileField(blank=True, editable=False, help_text='Original image upload retained for safe image reprocessing.', upload_to='products/gallery/originals/'),
        ),
    ]
