# Generated by Django 5.2.16 on 2026-09-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_beckman_official_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='playback_file',
            field=models.FileField(blank=True, upload_to='products/gallery/playback/'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='video_poster',
            field=models.ImageField(blank=True, upload_to='products/gallery/posters/'),
        ),
    ]
