# Generated by Django 5.2.16 on 2026-08-26 18:52

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_productrelateditem_image'),
        ('orders', '0002_order_item_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_number', models.CharField(default=orders.models.generate_inquiry_number, editable=False, max_length=32, unique=True)),
                ('product_name', models.CharField(max_length=180)),
                ('product_code', models.CharField(max_length=60)),
                ('product_category', models.CharField(max_length=120)),
                ('full_name', models.CharField(max_length=120)),
                ('organization', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('country', models.CharField(default='Somalia', max_length=80)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('responded', 'Responded'), ('closed', 'Closed')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='catalog.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='orders_prod_status_c1f042_idx')],
            },
        ),
    ]
