# Generated by Django 5.2.16 on 2026-08-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_productinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinquiry',
            name='product_group',
            field=models.CharField(blank=True, choices=[('laboratory', 'Laboratory'), ('medical', 'Medical Equipment'), ('dental', 'Dental Equipment')], default='', max_length=20),
        ),
    ]
