# Generated by Django 5.2.16 on 2026-09-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_productinquiry_product_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(default='info@somlab.so', max_length=254)),
                ('notifications_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Email settings',
                'verbose_name_plural': 'Email settings',
            },
        ),
    ]
