# Generated by Django 5.2.16 on 2026-09-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_inquiryemailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryemailsettings',
            name='app_password_encrypted',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='inquiryemailsettings',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='From email'),
        ),
        migrations.AddField(
            model_name='inquiryemailsettings',
            name='smtp_host',
            field=models.CharField(default='smtp.gmail.com', max_length=255, verbose_name='SMTP host'),
        ),
        migrations.AddField(
            model_name='inquiryemailsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, verbose_name='SMTP port'),
        ),
        migrations.AddField(
            model_name='inquiryemailsettings',
            name='smtp_username',
            field=models.EmailField(blank=True, max_length=254, verbose_name='SMTP username'),
        ),
        migrations.AddField(
            model_name='inquiryemailsettings',
            name='use_tls',
            field=models.BooleanField(default=True, verbose_name='Use TLS'),
        ),
    ]
